package activos.logic;
// Generated 30/05/2019 12:35:36 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;




/**
 * Activo generated by hbm2java
 */
@Entity
@Table(name="Activo"
    ,catalog="Activos"
)
public class Activo  implements java.io.Serializable {


     private String codigo;
     private Integer bien;
     private Integer funcionario;
     private String funcionarioNombre;
     private String descripcion;
     private String categoria;

    public Activo() {
    }

	
    public Activo(String codigo, Integer bien) {
        this.codigo = codigo;
        this.bien = bien;
    }
    public Activo(String codigo, Integer bien, Integer funcionario, String funcionarioNombre, String descripcion, String categoria) {
       this.codigo = codigo;
       this.bien = bien;
       this.funcionario = funcionario;
       this.funcionarioNombre = funcionarioNombre;
       this.descripcion = descripcion;
       this.categoria = categoria;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="codigo", unique=true, nullable=false)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bien", nullable=false)
    public Integer getBien() {
        return this.bien;
    }
    
    public void setBien(Integer bien) {
        this.bien = bien;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="funcionario", nullable=false)
    public Integer getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Integer funcionario) {
        this.funcionario = funcionario;
    }
    public String getFuncionarioNombre() {
        return this.funcionarioNombre;
    }
    
    public void setFuncionarioNombre(String funcionarioNombre) {
        this.funcionarioNombre = funcionarioNombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }




}


