package activos.logic;
// Generated 30/05/2019 12:35:36 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;





/**
 * Bien generated by hbm2java
 */
@Entity
@Table(name = "Bien",
         catalog = "Activos"
)
public class Bien  implements java.io.Serializable {


     private Integer idBien;
     private Integer categoria;
     private Integer solicitud;
     private String descripcion;
     private String cantidad;
     private String marca;
     private int precio;
     private String funcionario;
     private String estado;
     private String modelo;
     private String categoriaNombre;
     

    public Bien() {
    }

	
    public Bien(Integer solicitud, String descripcion, String cantidad, String marca, int precio, String estado, String modelo) {
        this.solicitud = solicitud;
        this.descripcion = descripcion;
        this.cantidad = cantidad;
        this.marca = marca;
        this.precio = precio;
        this.estado = estado;
        this.modelo = modelo;
    }
   
   @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idBien", unique = true, nullable = false)
    public Integer getIdBien() {
        return this.idBien;
    }
    
    public void setIdBien(Integer idBien) {
        this.idBien = idBien;
    }
    
     @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="categoria", nullable=false)
    public Integer getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Integer categoria) {
        this.categoria = categoria;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="solicitud", nullable=false)
    public Integer getSolicitud() {
        return this.solicitud;
    }
    
    public void setSolicitud(Integer solicitud) {
        this.solicitud = solicitud;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(String cantidad) {
        this.cantidad = cantidad;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public int getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(int precio) {
        this.precio = precio;
    }
    public String getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(String funcionario) {
        this.funcionario = funcionario;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getCategoriaNombre() {
        return this.categoriaNombre;
    }
    
    public void setCategoriaNombre(String categoriaNombre) {
        this.categoriaNombre = categoriaNombre;
    }
   

}


