package activos.logic;
// Generated 30/05/2019 12:35:36 AM by Hibernate Tools 4.3.1



/**
 * Dependencia generated by hbm2java
 */
public class Dependencia  implements java.io.Serializable {


     private Integer id;
     private String descripcion;
     
    public Dependencia() {
    }

	
    public Dependencia(String descripcion) {
        this.descripcion = descripcion;
    }
   
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
   

}


