package activos.logic;
// Generated 26/04/2019 05:23:55 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Funcionario generated by hbm2java
 */
@Entity
@Table(name="Funcionario"
    ,catalog="Activos"
)
public class Funcionario  implements java.io.Serializable {


     private Integer idFuncionario;
     private Integer dependencia;
     private String cedula;
     private String dependencia_1;
     private String nombre;
     private Set funcionariobiens = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Funcionario() {
    }

	
    public Funcionario(Integer dependencia, String cedula, String dependencia_1, String nombre) {
        this.dependencia = dependencia;
        this.cedula = cedula;
        this.dependencia_1 = dependencia_1;
        this.nombre = nombre;
    }
    public Funcionario(Integer dependencia, String cedula, String dependencia_1, String nombre, Set funcionariobiens, Set usuarios) {
       this.dependencia = dependencia;
       this.cedula = cedula;
       this.dependencia_1 = dependencia_1;
       this.nombre = nombre;
       this.funcionariobiens = funcionariobiens;
       this.usuarios = usuarios;
    }
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idFuncionario", unique=true, nullable=false)
    public Integer getIdFuncionario() {
        return this.idFuncionario;
    }
    
    public void setIdFuncionario(Integer idFuncionario) {
        this.idFuncionario = idFuncionario;
    }
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="dependencia", nullable=false)
    public Integer getDependencia() {
        return this.dependencia;
    }
    
    public void setDependencia(Integer dependencia) {
        this.dependencia = dependencia;
    }
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public String getDependencia_1() {
        return this.dependencia_1;
    }
    
    public void setDependencia_1(String dependencia_1) {
        this.dependencia_1 = dependencia_1;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getFuncionariobiens() {
        return this.funcionariobiens;
    }
    
    public void setFuncionariobiens(Set funcionariobiens) {
        this.funcionariobiens = funcionariobiens;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


