package activos.logic;
// Generated 30/05/2019 12:35:36 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Solicitud generated by hbm2java
 */
@Entity
@Table(name="Solicitud"
    ,catalog="Activos"
)
public class Solicitud  implements java.io.Serializable {


     private Integer idSolicitud;
     private Integer dependencia;
     private String estado;
     private String comprobante;
     private String fecha;
     private String tipo;
     private String rasonRechazo;
     private String dependecia;
     private String registrador;

    public Solicitud() {
    }

	
    public Solicitud(Integer dependencia, String estado, String comprobante, String fecha, String tipo, String dependecia, String registrador) {
        this.dependencia = dependencia;
        this.estado = estado;
        this.comprobante = comprobante;
        this.fecha = fecha;
        this.tipo = tipo;
        this.dependecia = dependecia;
        this.registrador = registrador;
    }
 
   @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idSolicitud", unique=true, nullable=false)
    public Integer getIdSolicitud() {
        return this.idSolicitud;
    }
    
    public void setIdSolicitud(Integer idSolicitud) {
        this.idSolicitud = idSolicitud;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="dependencia", nullable=false)
    public Integer getDependencia() {
        return this.dependencia;
    }
    
    public void setDependencia(Integer dependencia) {
        this.dependencia = dependencia;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getComprobante() {
        return this.comprobante;
    }
    
    public void setComprobante(String comprobante) {
        this.comprobante = comprobante;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getRasonRechazo() {
        return this.rasonRechazo;
    }
    
    public void setRasonRechazo(String rasonRechazo) {
        this.rasonRechazo = rasonRechazo;
    }
    public String getDependecia() {
        return this.dependecia;
    }
    
    public void setDependecia(String dependecia) {
        this.dependecia = dependecia;
    }
    public String getRegistrador() {
        return this.registrador;
    }
    
    public void setRegistrador(String registrador) {
        this.registrador = registrador;
    }
    

}


