package activos.logic;
// Generated 26/04/2019 05:23:55 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "Usuario",
         catalog = "Activos"
)
public class Usuario implements java.io.Serializable {

    private Integer id;
    private Integer dependencia;
    private Integer funcionario;
    private String nombre;
    private String rol;
    private String dependecia;
    private String password;

    public Usuario() {
    }

    public Usuario(Integer dependencia, Integer funcionario, String nombre, String rol, String dependecia, String password) {
        this.dependencia = dependencia;
        this.funcionario = funcionario;
        this.nombre = nombre;
        this.rol = rol;
        this.dependecia = dependecia;
        this.password = password;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "dependencia", nullable = false)
    public Integer getDependencia() {
        return this.dependencia;
    }

    public void setDependencia(Integer dependencia) {
        this.dependencia = dependencia;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "dependencia", nullable = false)
    public Integer getFuncionario() {
        return this.funcionario;
    }

    public void setFuncionario(Integer funcionario) {
        this.funcionario = funcionario;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getRol() {
        return this.rol;
    }

    public void setRol(String rol) {
        this.rol = rol;
    }

    public String getDependecia() {
        return this.dependecia;
    }

    public void setDependecia(String dependecia) {
        this.dependecia = dependecia;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

}
